services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./migrations:/app/migrations
      - ./matches.json:/app/matches.json
      - .env:/app/.env
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
