"""multi_match_campaigns

Revision ID: 115a4df3e3eb
Revises: 56aceff4a1bc
Create Date: 2026-05-25 00:39:54.311645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115a4df3e3eb'
down_revision: Union[str, None] = '56aceff4a1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_target_matches',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'match_id')
    )
    
    # Data migration: copy existing associations
    op.execute(
        """
        INSERT INTO campaign_target_matches (campaign_id, match_id)
        SELECT id, match_id FROM campaigns WHERE match_id IS NOT NULL
        """
    )

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('match_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'matches', ['match_id'], ['id'])

    op.drop_table('campaign_target_matches')
    # ### end Alembic commands ###
