"""add admin chat sessions and messages

Revision ID: 2aff0456c31a
Revises: ce9c6500596a
Create Date: 2026-06-30 16:16:26.560680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aff0456c31a'
down_revision: Union[str, None] = 'ce9c6500596a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('admin_chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('query_results', sa.JSON(), nullable=True),
    sa.Column('chart_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['admin_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_chat_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_chat_messages_session_id'))

    op.drop_table('admin_chat_messages')
    with op.batch_alter_table('admin_chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_chat_sessions_user_id'))

    op.drop_table('admin_chat_sessions')
    # ### end Alembic commands ###
