"""Add target and priority to system events

Revision ID: 2b2d5e8573a9
Revises: 9daccc4b3fa3
Create Date: 2026-05-01 10:44:26.892218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2d5e8573a9'
down_revision: Union[str, None] = '9daccc4b3fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_user_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=False))
        batch_op.create_foreign_key('fk_system_events_target_user', 'users', ['target_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_system_events_target_user', type_='foreignkey')
        batch_op.drop_column('priority')
        batch_op.drop_column('target_user_id')

    # ### end Alembic commands ###
