"""add_tournament_questions

Revision ID: 2b94e7556439
Revises: f203ed063860
Create Date: 2026-05-04 01:48:36.576082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b94e7556439'
down_revision: Union[str, None] = 'f203ed063860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('toggle', 'multiple_choice', 'dropdown', 'free_text', 'free_number', name='questiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('default_scoring_rules', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('allow_powerup', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_questions_tournament_id'), ['tournament_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_questions_tournament_id'))

    op.drop_table('tournament_questions')
    # ### end Alembic commands ###
