"""Add notification preferences to user mappings

Revision ID: 51193722e1bc
Revises: 1d0ef93e1772
Create Date: 2026-05-01 10:49:07.694289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51193722e1bc'
down_revision: Union[str, None] = '1d0ef93e1772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_user_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_user_mappings', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')

    # ### end Alembic commands ###
