"""Add sport to tournament

Revision ID: 5200cedf1d90
Revises: bca028de8f71
Create Date: 2026-06-16 19:30:34.736681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5200cedf1d90'
down_revision: Union[str, None] = 'bca028de8f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.String(), server_default='cricket', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('sport')

    # ### end Alembic commands ###
