"""Add campaign_id to LeaderboardEntry and make match_id nullable

Revision ID: 84ce0e0101f2
Revises: 32e6e6722430
Create Date: 2026-05-25 20:53:13.758331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ce0e0101f2'
down_revision: Union[str, None] = '32e6e6722430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.String(), nullable=True))
        batch_op.alter_column('match_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('uq_leaderboard_entry', type_='unique')
        batch_op.create_unique_constraint('uq_leaderboard_entry', ['user_id', 'match_id', 'campaign_id', 'league_id'])
        batch_op.create_index(batch_op.f('ix_leaderboard_entries_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_foreign_key('fk_leaderboard_entries_campaign_id', 'campaigns', ['campaign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leaderboard_entries_campaign_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leaderboard_entries_campaign_id'))
        batch_op.drop_constraint('uq_leaderboard_entry', type_='unique')
        batch_op.create_unique_constraint('uq_leaderboard_entry', ['user_id', 'match_id', 'league_id'])
        batch_op.alter_column('match_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
