"""Add system activity log

Revision ID: 9daccc4b3fa3
Revises: db56aaac3df3
Create Date: 2026-05-01 10:31:23.740303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9daccc4b3fa3'
down_revision: Union[str, None] = 'db56aaac3df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payload', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_foreign_key('fk_system_events_campaign_id', 'campaigns', ['campaign_id'], ['id'])
        batch_op.drop_column('event_metadata')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('event_metadata', sqlite.JSON(), nullable=False))
        batch_op.drop_constraint('fk_system_events_campaign_id', type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('payload')
        batch_op.drop_column('message')
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
