"""Add LLMCallLog model

Revision ID: b83255bdcbf1
Revises: 2aff0456c31a
Create Date: 2026-07-03 12:08:03.258587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83255bdcbf1'
down_revision: Union[str, None] = '2aff0456c31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caller', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('system_instruction', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('raw_request', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_logs_caller'), ['caller'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_tournament_id'), ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_caller'))

    op.drop_table('llm_call_logs')
    # ### end Alembic commands ###
