"""Add tournament rankings

Revision ID: bca028de8f71
Revises: e36d423db7e7
Create Date: 2026-06-16 19:15:53.082228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca028de8f71'
down_revision: Union[str, None] = 'e36d423db7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_team_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_team_rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_team_rankings_team_name'), ['team_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_team_rankings_tournament_id'), ['tournament_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_team_rankings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_team_rankings_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_team_rankings_team_name'))

    op.drop_table('tournament_team_rankings')
    # ### end Alembic commands ###
