"""Add model column to LLMCallLog

Revision ID: d298d34abc1b
Revises: b83255bdcbf1
Create Date: 2026-07-03 12:14:29.185002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd298d34abc1b'
down_revision: Union[str, None] = 'b83255bdcbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_llm_call_logs_model'), ['model'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_model'))
        batch_op.drop_column('model')

    # ### end Alembic commands ###
