"""add_user_alias_fields

Revision ID: d7c4ef7f6fa8
Revises: 2b94e7556439
Create Date: 2026-05-04 23:01:20.592927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c4ef7f6fa8'
down_revision: Union[str, None] = '2b94e7556439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('use_alias', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_alias'), ['alias'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_alias'))
        batch_op.drop_column('use_alias')
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
